# Site wide configuration

title:            "The Sopranos, Silicon Valley, and Summer Afternoons: A Day in my Life"
locale:           en_US
#url:              http://logicx24.github.io
url:              http://localhost:4000

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Aakash Japi
  avatar: me.jpg
  bio: "A movie-watching, book-loving, Software engineer and Entrepreneur from Berkeley."
  email: aakashjapi@berkeley.edu
  disqus-shortname: "The Sopranos, Silicon Valley, and Summer Afternoons: A Day in my Life"
  twitter: logicx24
  facebook: aakash.japi
  google:
    plus: #username
    analytics: 
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: logicx24
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: aakashjapi
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
